const diamondPatterns: { [key: string]: string[] } = {
  A: ['A'],
  B: [' A', 'B B', ' A'],
  C: ['  A', ' B B', 'C   C', ' B B', '  A'],
  D: ['   A', '  B B', ' C   C', 'D     D', ' C   C', '  B B', '   A'],
  E: [
    '    A',
    '   B B',
    '  C   C',
    ' D     D',
    'E       E',
    ' D     D',
    '  C   C',
    '   B B',
    '    A',
  ],
  F: [
    '     A',
    '    B B',
    '   C   C',
    '  D     D',
    ' E       E',
    'F         F',
    ' E       E',
    '  D     D',
    '   C   C',
    '    B B',
    '     A',
  ],
  G: [
    '      A',
    '     B B',
    '    C   C',
    '   D     D',
    '  E       E',
    ' F         F',
    'G           G',
    ' F         F',
    '  E       E',
    '   D     D',
    '    C   C',
    '     B B',
    '      A',
  ],
  H: [
    '       A',
    '      B B',
    '     C   C',
    '    D     D',
    '   E       E',
    '  F         F',
    ' G           G',
    'H             H',
    ' G           G',
    '  F         F',
    '   E       E',
    '    D     D',
    '     C   C',
    '      B B',
    '       A',
  ],
  I: [
    '        A',
    '       B B',
    '      C   C',
    '     D     D',
    '    E       E',
    '   F         F',
    '  G           G',
    ' H             H',
    'I               I',
    ' H             H',
    '  G           G',
    '   F         F',
    '    E       E',
    '     D     D',
    '      C   C',
    '       B B',
    '        A',
  ],
  J: [
    '         A',
    '        B B',
    '       C   C',
    '      D     D',
    '     E       E',
    '    F         F',
    '   G           G',
    '  H             H',
    ' I               I',
    'J                 J',
    ' I               I',
    '  H             H',
    '   G           G',
    '    F         F',
    '     E       E',
    '      D     D',
    '       C   C',
    '        B B',
    '         A',
  ],
  K: [
    '          A',
    '         B B',
    '        C   C',
    '       D     D',
    '      E       E',
    '     F         F',
    '    G           G',
    '   H             H',
    '  I               I',
    ' J                 J',
    'K                   K',
    ' J                 J',
    '  I               I',
    '   H             H',
    '    G           G',
    '     F         F',
    '      E       E',
    '       D     D',
    '        C   C',
    '         B B',
    '          A',
  ],
  L: [
    '           A',
    '          B B',
    '         C   C',
    '        D     D',
    '       E       E',
    '      F         F',
    '     G           G',
    '    H             H',
    '   I               I',
    '  J                 J',
    ' K                   K',
    'L                     L',
    ' K                   K',
    '  J                 J',
    '   I               I',
    '    H             H',
    '     G           G',
    '      F         F',
    '       E       E',
    '        D     D',
    '         C   C',
    '          B B',
    '           A',
  ],
  M: [
    '            A',
    '           B B',
    '          C   C',
    '         D     D',
    '        E       E',
    '       F         F',
    '      G           G',
    '     H             H',
    '    I               I',
    '   J                 J',
    '  K                   K',
    ' L                     L',
    'M                       M',
    ' L                     L',
    '  K                   K',
    '   J                 J',
    '    I               I',
    '     H             H',
    '      G           G',
    '       F         F',
    '        E       E',
    '         D     D',
    '          C   C',
    '           B B',
    '            A',
  ],
  N: [
    '             A',
    '            B B',
    '           C   C',
    '          D     D',
    '         E       E',
    '        F         F',
    '       G           G',
    '      H             H',
    '     I               I',
    '    J                 J',
    '   K                   K',
    '  L                     L',
    ' M                       M',
    'N                         N',
    ' M                       M',
    '  L                     L',
    '   K                   K',
    '    J                 J',
    '     I               I',
    '      H             H',
    '       G           G',
    '        F         F',
    '         E       E',
    '          D     D',
    '           C   C',
    '            B B',
    '             A',
  ],
  O: [
    '              A',
    '             B B',
    '            C   C',
    '           D     D',
    '          E       E',
    '         F         F',
    '        G           G',
    '       H             H',
    '      I               I',
    '     J                 J',
    '    K                   K',
    '   L                     L',
    '  M                       M',
    ' N                         N',
    'O                           O',
    ' N                         N',
    '  M                       M',
    '   L                     L',
    '    K                   K',
    '     J                 J',
    '      I               I',
    '       H             H',
    '        G           G',
    '         F         F',
    '          E       E',
    '           D     D',
    '            C   C',
    '             B B',
    '              A',
  ],
  P: [
    '               A',
    '              B B',
    '             C   C',
    '            D     D',
    '           E       E',
    '          F         F',
    '         G           G',
    '        H             H',
    '       I               I',
    '      J                 J',
    '     K                   K',
    '    L                     L',
    '   M                       M',
    '  N                         N',
    ' O                           O',
    'P                             P',
    ' O                           O',
    '  N                         N',
    '   M                       M',
    '    L                     L',
    '     K                   K',
    '      J                 J',
    '       I               I',
    '        H             H',
    '         G           G',
    '          F         F',
    '           E       E',
    '            D     D',
    '             C   C',
    '              B B',
    '               A',
  ],
  Q: [
    '                A',
    '               B B',
    '              C   C',
    '             D     D',
    '            E       E',
    '           F         F',
    '          G           G',
    '         H             H',
    '        I               I',
    '       J                 J',
    '      K                   K',
    '     L                     L',
    '    M                       M',
    '   N                         N',
    '  O                           O',
    ' P                             P',
    'Q                               Q',
    ' P                             P',
    '  O                           O',
    '   N                         N',
    '    M                       M',
    '     L                     L',
    '      K                   K',
    '       J                 J',
    '        I               I',
    '         H             H',
    '          G           G',
    '           F         F',
    '            E       E',
    '             D     D',
    '              C   C',
    '               B B',
    '                A',
  ],
  R: [
    '                 A',
    '                B B',
    '               C   C',
    '              D     D',
    '             E       E',
    '            F         F',
    '           G           G',
    '          H             H',
    '         I               I',
    '        J                 J',
    '       K                   K',
    '      L                     L',
    '     M                       M',
    '    N                         N',
    '   O                           O',
    '  P                             P',
    ' Q                               Q',
    'R                                 R',
    ' Q                               Q',
    '  P                             P',
    '   O                           O',
    '    N                         N',
    '     M                       M',
    '      L                     L',
    '       K                   K',
    '        J                 J',
    '         I               I',
    '          H             H',
    '           G           G',
    '            F         F',
    '             E       E',
    '              D     D',
    '               C   C',
    '                B B',
    '                 A',
  ],
  S: [
    '                  A',
    '                 B B',
    '                C   C',
    '               D     D',
    '              E       E',
    '             F         F',
    '            G           G',
    '           H             H',
    '          I               I',
    '         J                 J',
    '        K                   K',
    '       L                     L',
    '      M                       M',
    '     N                         N',
    '    O                           O',
    '   P                             P',
    '  Q                               Q',
    ' R                                 R',
    'S                                   S',
    ' R                                 R',
    '  Q                               Q',
    '   P                             P',
    '    O                           O',
    '     N                         N',
    '      M                       M',
    '       L                     L',
    '        K                   K',
    '         J                 J',
    '          I               I',
    '           H             H',
    '            G           G',
    '             F         F',
    '              E       E',
    '               D     D',
    '                C   C',
    '                 B B',
    '                  A',
  ],
  T: [
    '                   A',
    '                  B B',
    '                 C   C',
    '                D     D',
    '               E       E',
    '              F         F',
    '             G           G',
    '            H             H',
    '           I               I',
    '          J                 J',
    '         K                   K',
    '        L                     L',
    '       M                       M',
    '      N                         N',
    '     O                           O',
    '    P                             P',
    '   Q                               Q',
    '  R                                 R',
    ' S                                   S',
    'T                                     T',
    ' S                                   S',
    '  R                                 R',
    '   Q                               Q',
    '    P                             P',
    '     O                           O',
    '      N                         N',
    '       M                       M',
    '        L                     L',
    '         K                   K',
    '          J                 J',
    '           I               I',
    '            H             H',
    '             G           G',
    '              F         F',
    '               E       E',
    '                D     D',
    '                 C   C',
    '                  B B',
    '                   A',
  ],
  U: [
    '                    A',
    '                   B B',
    '                  C   C',
    '                 D     D',
    '                E       E',
    '               F         F',
    '              G           G',
    '             H             H',
    '            I               I',
    '           J                 J',
    '          K                   K',
    '         L                     L',
    '        M                       M',
    '       N                         N',
    '      O                           O',
    '     P                             P',
    '    Q                               Q',
    '   R                                 R',
    '  S                                   S',
    ' T                                     T',
    'U                                       U',
    ' T                                     T',
    '  S                                   S',
    '   R                                 R',
    '    Q                               Q',
    '     P                             P',
    '      O                           O',
    '       N                         N',
    '        M                       M',
    '         L                     L',
    '          K                   K',
    '           J                 J',
    '            I               I',
    '             H             H',
    '              G           G',
    '               F         F',
    '                E       E',
    '                 D     D',
    '                  C   C',
    '                   B B',
    '                    A',
  ],
  V: [
    '                     A',
    '                    B B',
    '                   C   C',
    '                  D     D',
    '                 E       E',
    '                F         F',
    '               G           G',
    '              H             H',
    '             I               I',
    '            J                 J',
    '           K                   K',
    '          L                     L',
    '         M                       M',
    '        N                         N',
    '       O                           O',
    '      P                             P',
    '     Q                               Q',
    '    R                                 R',
    '   S                                   S',
    '  T                                     T',
    ' U                                       U',
    'V                                         V',
    ' U                                       U',
    '  T                                     T',
    '   S                                   S',
    '    R                                 R',
    '     Q                               Q',
    '      P                             P',
    '       O                           O',
    '        N                         N',
    '         M                       M',
    '          L                     L',
    '           K                   K',
    '            J                 J',
    '             I               I',
    '              H             H',
    '               G           G',
    '                F         F',
    '                 E       E',
    '                  D     D',
    '                   C   C',
    '                    B B',
    '                     A',
  ],
  W: [
    '                      A',
    '                     B B',
    '                    C   C',
    '                   D     D',
    '                  E       E',
    '                 F         F',
    '                G           G',
    '               H             H',
    '              I               I',
    '             J                 J',
    '            K                   K',
    '           L                     L',
    '          M                       M',
    '         N                         N',
    '        O                           O',
    '       P                             P',
    '      Q                               Q',
    '     R                                 R',
    '    S                                   S',
    '   T                                     T',
    '  U                                       U',
    ' V                                         V',
    'W                                           W',
    ' V                                         V',
    '  U                                       U',
    '   T                                     T',
    '    S                                   S',
    '     R                                 R',
    '      Q                               Q',
    '       P                             P',
    '        O                           O',
    '         N                         N',
    '          M                       M',
    '           L                     L',
    '            K                   K',
    '             J                 J',
    '              I               I',
    '               H             H',
    '                G           G',
    '                 F         F',
    '                  E       E',
    '                   D     D',
    '                    C   C',
    '                     B B',
    '                      A',
  ],
  X: [
    '                       A',
    '                      B B',
    '                     C   C',
    '                    D     D',
    '                   E       E',
    '                  F         F',
    '                 G           G',
    '                H             H',
    '               I               I',
    '              J                 J',
    '             K                   K',
    '            L                     L',
    '           M                       M',
    '          N                         N',
    '         O                           O',
    '        P                             P',
    '       Q                               Q',
    '      R                                 R',
    '     S                                   S',
    '    T                                     T',
    '   U                                       U',
    '  V                                         V',
    ' W                                           W',
    'X                                             X',
    ' W                                           W',
    '  V                                         V',
    '   U                                       U',
    '    T                                     T',
    '     S                                   S',
    '      R                                 R',
    '       Q                               Q',
    '        P                             P',
    '         O                           O',
    '          N                         N',
    '           M                       M',
    '            L                     L',
    '             K                   K',
    '              J                 J',
    '               I               I',
    '                H             H',
    '                 G           G',
    '                  F         F',
    '                   E       E',
    '                    D     D',
    '                     C   C',
    '                      B B',
    '                       A',
  ],
  Y: [
    '                        A',
    '                       B B',
    '                      C   C',
    '                     D     D',
    '                    E       E',
    '                   F         F',
    '                  G           G',
    '                 H             H',
    '                I               I',
    '               J                 J',
    '              K                   K',
    '             L                     L',
    '            M                       M',
    '           N                         N',
    '          O                           O',
    '         P                             P',
    '        Q                               Q',
    '       R                                 R',
    '      S                                   S',
    '     T                                     T',
    '    U                                       U',
    '   V                                         V',
    '  W                                           W',
    ' X                                             X',
    'Y                                               Y',
    ' X                                             X',
    '  W                                           W',
    '   V                                         V',
    '    U                                       U',
    '     T                                     T',
    '      S                                   S',
    '       R                                 R',
    '        Q                               Q',
    '         P                             P',
    '          O                           O',
    '           N                         N',
    '            M                       M',
    '             L                     L',
    '              K                   K',
    '               J                 J',
    '                I               I',
    '                 H             H',
    '                  G           G',
    '                   F         F',
    '                    E       E',
    '                     D     D',
    '                      C   C',
    '                       B B',
    '                        A',
  ],
  Z: [
    '                         A',
    '                        B B',
    '                       C   C',
    '                      D     D',
    '                     E       E',
    '                    F         F',
    '                   G           G',
    '                  H             H',
    '                 I               I',
    '                J                 J',
    '               K                   K',
    '              L                     L',
    '             M                       M',
    '            N                         N',
    '           O                           O',
    '          P                             P',
    '         Q                               Q',
    '        R                                 R',
    '       S                                   S',
    '      T                                     T',
    '     U                                       U',
    '    V                                         V',
    '   W                                           W',
    '  X                                             X',
    ' Y                                               Y',
    'Z                                                 Z',
    ' Y                                               Y',
    '  X                                             X',
    '   W                                           W',
    '    V                                         V',
    '     U                                       U',
    '      T                                     T',
    '       S                                   S',
    '        R                                 R',
    '         Q                               Q',
    '          P                             P',
    '           O                           O',
    '            N                         N',
    '             M                       M',
    '              L                     L',
    '               K                   K',
    '                J                 J',
    '                 I               I',
    '                  H             H',
    '                   G           G',
    '                    F         F',
    '                     E       E',
    '                      D     D',
    '                       C   C',
    '                        B B',
    '                         A',
  ],
};

export default diamondPatterns;
